#!/bin/sh

[ -z "$DEVPATH" ] && exit 0
[ "$SUBSYSTEM" != "drivers" ] && exit 0

[ -e /etc/ccw.conf ] || exit 1

while read line; do
    OLDIFS=$IFS
    IFS=",$IFS"
    set - $line
    IFS=$OLDIFS
    /sbin/chzdev -e -a $1 $2:$3:$4 $5 $6
done < /etc/ccw.conf
